// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAlmacen.Persistence;

#nullable disable

namespace SistemaAlmacen.Persistence.Migrations
{
    [DbContext(typeof(SistemaAlmacenDbContext))]
    partial class SistemaAlmacenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaAlmacen.Domain.Entities.Almacen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<Guid>("LocalidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Almacenes", (string)null);
                });

            modelBuilder.Entity("SistemaAlmacen.Domain.Entities.Almacen", b =>
                {
                    b.OwnsOne("SistemaAlmacen.Domain.ValueObjects.CodigoVO", "Codigo", b1 =>
                        {
                            b1.Property<Guid>("AlmacenId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("varchar(5)")
                                .HasColumnName("Codigo");

                            b1.HasKey("AlmacenId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("Almacenes");

                            b1.WithOwner()
                                .HasForeignKey("AlmacenId");
                        });

                    b.OwnsOne("SistemaAlmacen.Domain.ValueObjects.TelefonoVO", "Telefono", b1 =>
                        {
                            b1.Property<Guid>("AlmacenId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("varchar(10)")
                                .HasColumnName("Telefono");

                            b1.HasKey("AlmacenId");

                            b1.ToTable("Almacenes");

                            b1.WithOwner()
                                .HasForeignKey("AlmacenId");
                        });

                    b.Navigation("Codigo")
                        .IsRequired();

                    b.Navigation("Telefono")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
